// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: app/shop/rpc/shop.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PricePoints   int64                  `protobuf:"varint,4,opt,name=price_points,json=pricePoints,proto3" json:"price_points,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	SalesStatus   string                 `protobuf:"bytes,9,opt,name=sales_status,json=salesStatus,proto3" json:"sales_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{0}
}

func (x *ItemInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemInfo) GetPricePoints() int64 {
	if x != nil {
		return x.PricePoints
	}
	return 0
}

func (x *ItemInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ItemInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ItemInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ItemInfo) GetSalesStatus() string {
	if x != nil {
		return x.SalesStatus
	}
	return ""
}

type ItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        int64                  `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsRequest) Reset() {
	*x = ItemsRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsRequest) ProtoMessage() {}

func (x *ItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsRequest.ProtoReflect.Descriptor instead.
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{1}
}

func (x *ItemsRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *ItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfo            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsResponse) Reset() {
	*x = ItemsResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsResponse) ProtoMessage() {}

func (x *ItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsResponse.ProtoReflect.Descriptor instead.
func (*ItemsResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{2}
}

func (x *ItemsResponse) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemsResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *ItemsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type RedeemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemRequest) Reset() {
	*x = RedeemRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemRequest) ProtoMessage() {}

func (x *RedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemRequest.ProtoReflect.Descriptor instead.
func (*RedeemRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{3}
}

func (x *RedeemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RedeemRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RedeemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RedeemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemResponse) Reset() {
	*x = RedeemResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemResponse) ProtoMessage() {}

func (x *RedeemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemResponse.ProtoReflect.Descriptor instead.
func (*RedeemResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{4}
}

func (x *RedeemResponse) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	PointsSpent   int64                  `protobuf:"varint,5,opt,name=points_spent,json=pointsSpent,proto3" json:"points_spent,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,6,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	ActivityId    int64                  `protobuf:"varint,7,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{5}
}

func (x *OrderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *OrderInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *OrderInfo) GetPointsSpent() int64 {
	if x != nil {
		return x.PointsSpent
	}
	return 0
}

func (x *OrderInfo) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *OrderInfo) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type OrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Cursor        int64                  `protobuf:"varint,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersRequest) Reset() {
	*x = OrdersRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersRequest) ProtoMessage() {}

func (x *OrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersRequest.ProtoReflect.Descriptor instead.
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{6}
}

func (x *OrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrdersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrdersRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *OrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersResponse) Reset() {
	*x = OrdersResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersResponse) ProtoMessage() {}

func (x *OrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersResponse.ProtoReflect.Descriptor instead.
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{7}
}

func (x *OrdersResponse) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *OrdersResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *OrdersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type OrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailRequest) Reset() {
	*x = OrderDetailRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailRequest) ProtoMessage() {}

func (x *OrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailRequest.ProtoReflect.Descriptor instead.
func (*OrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{8}
}

func (x *OrderDetailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderDetailRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type OrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDetailResponse) Reset() {
	*x = OrderDetailResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailResponse) ProtoMessage() {}

func (x *OrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailResponse.ProtoReflect.Descriptor instead.
func (*OrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{9}
}

func (x *OrderDetailResponse) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

type FlashActivityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LimitQty      int32                  `protobuf:"varint,6,opt,name=limit_qty,json=limitQty,proto3" json:"limit_qty,omitempty"`
	SoldQty       int32                  `protobuf:"varint,7,opt,name=sold_qty,json=soldQty,proto3" json:"sold_qty,omitempty"`
	PerUserLimit  int32                  `protobuf:"varint,8,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`
	PricePoints   int64                  `protobuf:"varint,9,opt,name=price_points,json=pricePoints,proto3" json:"price_points,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	SalesStatus   string                 `protobuf:"bytes,11,opt,name=sales_status,json=salesStatus,proto3" json:"sales_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashActivityInfo) Reset() {
	*x = FlashActivityInfo{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashActivityInfo) ProtoMessage() {}

func (x *FlashActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashActivityInfo.ProtoReflect.Descriptor instead.
func (*FlashActivityInfo) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{10}
}

func (x *FlashActivityInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlashActivityInfo) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *FlashActivityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlashActivityInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FlashActivityInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FlashActivityInfo) GetLimitQty() int32 {
	if x != nil {
		return x.LimitQty
	}
	return 0
}

func (x *FlashActivityInfo) GetSoldQty() int32 {
	if x != nil {
		return x.SoldQty
	}
	return 0
}

func (x *FlashActivityInfo) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *FlashActivityInfo) GetPricePoints() int64 {
	if x != nil {
		return x.PricePoints
	}
	return 0
}

func (x *FlashActivityInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FlashActivityInfo) GetSalesStatus() string {
	if x != nil {
		return x.SalesStatus
	}
	return ""
}

type FlashActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashActivitiesRequest) Reset() {
	*x = FlashActivitiesRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashActivitiesRequest) ProtoMessage() {}

func (x *FlashActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashActivitiesRequest.ProtoReflect.Descriptor instead.
func (*FlashActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{11}
}

func (x *FlashActivitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FlashActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*FlashActivityInfo   `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashActivitiesResponse) Reset() {
	*x = FlashActivitiesResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashActivitiesResponse) ProtoMessage() {}

func (x *FlashActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashActivitiesResponse.ProtoReflect.Descriptor instead.
func (*FlashActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{12}
}

func (x *FlashActivitiesResponse) GetActivities() []*FlashActivityInfo {
	if x != nil {
		return x.Activities
	}
	return nil
}

type FlashRedeemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityId    int64                  `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashRedeemRequest) Reset() {
	*x = FlashRedeemRequest{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashRedeemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashRedeemRequest) ProtoMessage() {}

func (x *FlashRedeemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashRedeemRequest.ProtoReflect.Descriptor instead.
func (*FlashRedeemRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{13}
}

func (x *FlashRedeemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FlashRedeemRequest) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *FlashRedeemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type FlashRedeemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlashRedeemResponse) Reset() {
	*x = FlashRedeemResponse{}
	mi := &file_app_shop_rpc_shop_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashRedeemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashRedeemResponse) ProtoMessage() {}

func (x *FlashRedeemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_rpc_shop_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashRedeemResponse.ProtoReflect.Descriptor instead.
func (*FlashRedeemResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_rpc_shop_proto_rawDescGZIP(), []int{14}
}

func (x *FlashRedeemResponse) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_app_shop_rpc_shop_proto protoreflect.FileDescriptor

const file_app_shop_rpc_shop_proto_rawDesc = "" +
	"\n" +
	"\x17app/shop/rpc/shop.proto\x12\x04shop\"\x82\x02\n" +
	"\bItemInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fprice_points\x18\x04 \x01(\x03R\vpricePoints\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12!\n" +
	"\fsales_status\x18\t \x01(\tR\vsalesStatus\"X\n" +
	"\fItemsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"q\n" +
	"\rItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.shop.ItemInfoR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"]\n" +
	"\rRedeemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"7\n" +
	"\x0eRedeemResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.shop.OrderInfoR\x05order\"\xf0\x01\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x03R\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12!\n" +
	"\fpoints_spent\x18\x05 \x01(\x03R\vpointsSpent\x12!\n" +
	"\forder_status\x18\x06 \x01(\tR\vorderStatus\x12\x1f\n" +
	"\vactivity_id\x18\a \x01(\x03R\n" +
	"activityId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"n\n" +
	"\rOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"u\n" +
	"\x0eOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.shop.OrderInfoR\x06orders\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"H\n" +
	"\x12OrderDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\"<\n" +
	"\x13OrderDetailResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.shop.OrderInfoR\x05order\"\xc6\x02\n" +
	"\x11FlashActivityInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1b\n" +
	"\tlimit_qty\x18\x06 \x01(\x05R\blimitQty\x12\x19\n" +
	"\bsold_qty\x18\a \x01(\x05R\asoldQty\x12$\n" +
	"\x0eper_user_limit\x18\b \x01(\x05R\fperUserLimit\x12!\n" +
	"\fprice_points\x18\t \x01(\x03R\vpricePoints\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\fsales_status\x18\v \x01(\tR\vsalesStatus\".\n" +
	"\x16FlashActivitiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"R\n" +
	"\x17FlashActivitiesResponse\x127\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x17.shop.FlashActivityInfoR\n" +
	"activities\"j\n" +
	"\x12FlashRedeemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x03R\n" +
	"activityId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"<\n" +
	"\x13FlashRedeemResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.shop.OrderInfoR\x05order2\xfa\x02\n" +
	"\x04Shop\x120\n" +
	"\x05Items\x12\x12.shop.ItemsRequest\x1a\x13.shop.ItemsResponse\x123\n" +
	"\x06Redeem\x12\x13.shop.RedeemRequest\x1a\x14.shop.RedeemResponse\x123\n" +
	"\x06Orders\x12\x13.shop.OrdersRequest\x1a\x14.shop.OrdersResponse\x12B\n" +
	"\vOrderDetail\x12\x18.shop.OrderDetailRequest\x1a\x19.shop.OrderDetailResponse\x12N\n" +
	"\x0fFlashActivities\x12\x1c.shop.FlashActivitiesRequest\x1a\x1d.shop.FlashActivitiesResponse\x12B\n" +
	"\vFlashRedeem\x12\x18.shop.FlashRedeemRequest\x1a\x19.shop.FlashRedeemResponseB4Z2github.com/cdcdx/hc-framework-go/app/shop/rpc/shopb\x06proto3"

var (
	file_app_shop_rpc_shop_proto_rawDescOnce sync.Once
	file_app_shop_rpc_shop_proto_rawDescData []byte
)

func file_app_shop_rpc_shop_proto_rawDescGZIP() []byte {
	file_app_shop_rpc_shop_proto_rawDescOnce.Do(func() {
		file_app_shop_rpc_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_shop_rpc_shop_proto_rawDesc), len(file_app_shop_rpc_shop_proto_rawDesc)))
	})
	return file_app_shop_rpc_shop_proto_rawDescData
}

var file_app_shop_rpc_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_app_shop_rpc_shop_proto_goTypes = []any{
	(*ItemInfo)(nil),                // 0: shop.ItemInfo
	(*ItemsRequest)(nil),            // 1: shop.ItemsRequest
	(*ItemsResponse)(nil),           // 2: shop.ItemsResponse
	(*RedeemRequest)(nil),           // 3: shop.RedeemRequest
	(*RedeemResponse)(nil),          // 4: shop.RedeemResponse
	(*OrderInfo)(nil),               // 5: shop.OrderInfo
	(*OrdersRequest)(nil),           // 6: shop.OrdersRequest
	(*OrdersResponse)(nil),          // 7: shop.OrdersResponse
	(*OrderDetailRequest)(nil),      // 8: shop.OrderDetailRequest
	(*OrderDetailResponse)(nil),     // 9: shop.OrderDetailResponse
	(*FlashActivityInfo)(nil),       // 10: shop.FlashActivityInfo
	(*FlashActivitiesRequest)(nil),  // 11: shop.FlashActivitiesRequest
	(*FlashActivitiesResponse)(nil), // 12: shop.FlashActivitiesResponse
	(*FlashRedeemRequest)(nil),      // 13: shop.FlashRedeemRequest
	(*FlashRedeemResponse)(nil),     // 14: shop.FlashRedeemResponse
}
var file_app_shop_rpc_shop_proto_depIdxs = []int32{
	0,  // 0: shop.ItemsResponse.items:type_name -> shop.ItemInfo
	5,  // 1: shop.RedeemResponse.order:type_name -> shop.OrderInfo
	5,  // 2: shop.OrdersResponse.orders:type_name -> shop.OrderInfo
	5,  // 3: shop.OrderDetailResponse.order:type_name -> shop.OrderInfo
	10, // 4: shop.FlashActivitiesResponse.activities:type_name -> shop.FlashActivityInfo
	5,  // 5: shop.FlashRedeemResponse.order:type_name -> shop.OrderInfo
	1,  // 6: shop.Shop.Items:input_type -> shop.ItemsRequest
	3,  // 7: shop.Shop.Redeem:input_type -> shop.RedeemRequest
	6,  // 8: shop.Shop.Orders:input_type -> shop.OrdersRequest
	8,  // 9: shop.Shop.OrderDetail:input_type -> shop.OrderDetailRequest
	11, // 10: shop.Shop.FlashActivities:input_type -> shop.FlashActivitiesRequest
	13, // 11: shop.Shop.FlashRedeem:input_type -> shop.FlashRedeemRequest
	2,  // 12: shop.Shop.Items:output_type -> shop.ItemsResponse
	4,  // 13: shop.Shop.Redeem:output_type -> shop.RedeemResponse
	7,  // 14: shop.Shop.Orders:output_type -> shop.OrdersResponse
	9,  // 15: shop.Shop.OrderDetail:output_type -> shop.OrderDetailResponse
	12, // 16: shop.Shop.FlashActivities:output_type -> shop.FlashActivitiesResponse
	14, // 17: shop.Shop.FlashRedeem:output_type -> shop.FlashRedeemResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_app_shop_rpc_shop_proto_init() }
func file_app_shop_rpc_shop_proto_init() {
	if File_app_shop_rpc_shop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_shop_rpc_shop_proto_rawDesc), len(file_app_shop_rpc_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_shop_rpc_shop_proto_goTypes,
		DependencyIndexes: file_app_shop_rpc_shop_proto_depIdxs,
		MessageInfos:      file_app_shop_rpc_shop_proto_msgTypes,
	}.Build()
	File_app_shop_rpc_shop_proto = out.File
	file_app_shop_rpc_shop_proto_goTypes = nil
	file_app_shop_rpc_shop_proto_depIdxs = nil
}
