// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto（手写等价版，pb 生成后即可用）

package shop

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// Shop shop-rpc 客户端接口
	Shop interface {
		Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error)
		Redeem(ctx context.Context, in *RedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
		Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
		OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error)
		FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error)
		FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
	}

	defaultShop struct {
		cli zrpc.Client
	}
)

// NewShop 创建 shop-rpc 客户端
func NewShop(cli zrpc.Client) Shop {
	return &defaultShop{cli: cli}
}

func (m *defaultShop) Items(ctx context.Context, in *ItemsRequest, opts ...grpc.CallOption) (*ItemsResponse, error) {
	client := NewShopClient(m.cli.Conn())
	return client.Items(ctx, in, opts...)
}

func (m *defaultShop) Redeem(ctx context.Context, in *RedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	client := NewShopClient(m.cli.Conn())
	return client.Redeem(ctx, in, opts...)
}

func (m *defaultShop) Orders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	client := NewShopClient(m.cli.Conn())
	return client.Orders(ctx, in, opts...)
}

func (m *defaultShop) OrderDetail(ctx context.Context, in *OrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := NewShopClient(m.cli.Conn())
	return client.OrderDetail(ctx, in, opts...)
}

func (m *defaultShop) FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error) {
	client := NewShopClient(m.cli.Conn())
	return client.FlashActivities(ctx, in, opts...)
}

func (m *defaultShop) FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	client := NewShopClient(m.cli.Conn())
	return client.FlashRedeem(ctx, in, opts...)
}
