// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: app/rpc/hc.proto

package hc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hc_Register_FullMethodName        = "/hc.Hc/Register"
	Hc_Login_FullMethodName           = "/hc.Hc/Login"
	Hc_GoogleOAuth_FullMethodName     = "/hc.Hc/GoogleOAuth"
	Hc_RefreshToken_FullMethodName    = "/hc.Hc/RefreshToken"
	Hc_ChangePassword_FullMethodName  = "/hc.Hc/ChangePassword"
	Hc_GetProfile_FullMethodName      = "/hc.Hc/GetProfile"
	Hc_UpdateProfile_FullMethodName   = "/hc.Hc/UpdateProfile"
	Hc_GetPoints_FullMethodName       = "/hc.Hc/GetPoints"
	Hc_AddPoints_FullMethodName       = "/hc.Hc/AddPoints"
	Hc_DeductPoints_FullMethodName    = "/hc.Hc/DeductPoints"
	Hc_IdleStart_FullMethodName       = "/hc.Hc/IdleStart"
	Hc_IdleHeartbeat_FullMethodName   = "/hc.Hc/IdleHeartbeat"
	Hc_IdleStop_FullMethodName        = "/hc.Hc/IdleStop"
	Hc_IdleStopDevice_FullMethodName  = "/hc.Hc/IdleStopDevice"
	Hc_IdleStatus_FullMethodName      = "/hc.Hc/IdleStatus"
	Hc_IdleRecords_FullMethodName     = "/hc.Hc/IdleRecords"
	Hc_TaskList_FullMethodName        = "/hc.Hc/TaskList"
	Hc_TaskProgress_FullMethodName    = "/hc.Hc/TaskProgress"
	Hc_TaskClaim_FullMethodName       = "/hc.Hc/TaskClaim"
	Hc_ReportProgress_FullMethodName  = "/hc.Hc/ReportProgress"
	Hc_ShopItems_FullMethodName       = "/hc.Hc/ShopItems"
	Hc_ShopRedeem_FullMethodName      = "/hc.Hc/ShopRedeem"
	Hc_ShopOrders_FullMethodName      = "/hc.Hc/ShopOrders"
	Hc_ShopOrderDetail_FullMethodName = "/hc.Hc/ShopOrderDetail"
	Hc_FlashActivities_FullMethodName = "/hc.Hc/FlashActivities"
	Hc_FlashRedeem_FullMethodName     = "/hc.Hc/FlashRedeem"
)

// HcClient is the client API for Hc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hc 单一领域 rpc：合并 user / idle / task / shop 四个领域（2 进程架构：网关 + 本 rpc）。
// 方法名按领域加前缀（Idle*/Task*/Shop*），user 域方法名本身域特定故不加前缀。
// 域间协作（积分增减 / 任务进度）在进程内直接调用，不再走跨 rpc。
type HcClient interface {
	// ================= user 域：认证 + 用户 + 积分 =================
	// 邮箱注册，成功直接签发 token 对
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 邮箱密码登录
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Google OAuth 登录/注册
	GoogleOAuth(ctx context.Context, in *GoogleOAuthRequest, opts ...grpc.CallOption) (*GoogleOAuthResponse, error)
	// 刷新 token
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	// 修改密码（校验旧密码，并使已签发 token 失效）
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	// 用户资料
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	// 积分余额
	GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error)
	// 加分（挂机/任务奖励入账）
	AddPoints(ctx context.Context, in *AddPointsRequest, opts ...grpc.CallOption) (*AddPointsResponse, error)
	// 扣分（兑换扣款，余额不足报错）
	DeductPoints(ctx context.Context, in *DeductPointsRequest, opts ...grpc.CallOption) (*DeductPointsResponse, error)
	// ================= idle 域：挂机 =================
	// 开始挂机（同设备幂等续期；设备数量超限报错）
	IdleStart(ctx context.Context, in *IdleStartRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	// 心跳上报（更新最后心跳时间）
	IdleHeartbeat(ctx context.Context, in *IdleHeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
	// 停止全部设备挂机并结算
	IdleStop(ctx context.Context, in *IdleStopRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	// 停止指定设备挂机并结算
	IdleStopDevice(ctx context.Context, in *IdleStopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	// 挂机状态（活跃会话 + 今日已赚积分）
	IdleStatus(ctx context.Context, in *IdleStatusRequest, opts ...grpc.CallOption) (*IdleStatusResponse, error)
	// 历史记录（游标分页）
	IdleRecords(ctx context.Context, in *IdleRecordsRequest, opts ...grpc.CallOption) (*IdleRecordsResponse, error)
	// ================= task 域：任务 =================
	// 任务列表（含当前用户进度）
	TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
	// 进度总览
	TaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (*TaskProgressResponse, error)
	// 领取任务奖励（进程内调用 AddPoints 入账）
	TaskClaim(ctx context.Context, in *TaskClaimRequest, opts ...grpc.CallOption) (*TaskClaimResponse, error)
	// 上报进度增量（登录/挂机结算/兑换完成事件驱动）
	ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error)
	// ================= shop 域：商城 + 抢购 =================
	// 商品列表（游标分页 + 分类筛选）
	ShopItems(ctx context.Context, in *ShopItemsRequest, opts ...grpc.CallOption) (*ShopItemsResponse, error)
	// 积分兑换（扣积分 + 扣库存 + 建单）
	ShopRedeem(ctx context.Context, in *ShopRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
	// 兑换订单列表
	ShopOrders(ctx context.Context, in *ShopOrdersRequest, opts ...grpc.CallOption) (*ShopOrdersResponse, error)
	// 订单详情（校验归属）
	ShopOrderDetail(ctx context.Context, in *ShopOrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error)
	// 进行中的抢购活动列表
	FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error)
	// 定时抢购（限量内入库，超出直接拒绝）
	FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
}

type hcClient struct {
	cc grpc.ClientConnInterface
}

func NewHcClient(cc grpc.ClientConnInterface) HcClient {
	return &hcClient{cc}
}

func (c *hcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Hc_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Hc_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) GoogleOAuth(ctx context.Context, in *GoogleOAuthRequest, opts ...grpc.CallOption) (*GoogleOAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleOAuthResponse)
	err := c.cc.Invoke(ctx, Hc_GoogleOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, Hc_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, Hc_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, Hc_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, Hc_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPointsResponse)
	err := c.cc.Invoke(ctx, Hc_GetPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) AddPoints(ctx context.Context, in *AddPointsRequest, opts ...grpc.CallOption) (*AddPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPointsResponse)
	err := c.cc.Invoke(ctx, Hc_AddPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) DeductPoints(ctx context.Context, in *DeductPointsRequest, opts ...grpc.CallOption) (*DeductPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductPointsResponse)
	err := c.cc.Invoke(ctx, Hc_DeductPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleStart(ctx context.Context, in *IdleStartRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Hc_IdleStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleHeartbeat(ctx context.Context, in *IdleHeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Hc_IdleHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleStop(ctx context.Context, in *IdleStopRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Hc_IdleStop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleStopDevice(ctx context.Context, in *IdleStopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Hc_IdleStopDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleStatus(ctx context.Context, in *IdleStatusRequest, opts ...grpc.CallOption) (*IdleStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleStatusResponse)
	err := c.cc.Invoke(ctx, Hc_IdleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) IdleRecords(ctx context.Context, in *IdleRecordsRequest, opts ...grpc.CallOption) (*IdleRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecordsResponse)
	err := c.cc.Invoke(ctx, Hc_IdleRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListResponse)
	err := c.cc.Invoke(ctx, Hc_TaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) TaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (*TaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskProgressResponse)
	err := c.cc.Invoke(ctx, Hc_TaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) TaskClaim(ctx context.Context, in *TaskClaimRequest, opts ...grpc.CallOption) (*TaskClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskClaimResponse)
	err := c.cc.Invoke(ctx, Hc_TaskClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Hc_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ShopItems(ctx context.Context, in *ShopItemsRequest, opts ...grpc.CallOption) (*ShopItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopItemsResponse)
	err := c.cc.Invoke(ctx, Hc_ShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ShopRedeem(ctx context.Context, in *ShopRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemResponse)
	err := c.cc.Invoke(ctx, Hc_ShopRedeem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ShopOrders(ctx context.Context, in *ShopOrdersRequest, opts ...grpc.CallOption) (*ShopOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShopOrdersResponse)
	err := c.cc.Invoke(ctx, Hc_ShopOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) ShopOrderDetail(ctx context.Context, in *ShopOrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderInfo)
	err := c.cc.Invoke(ctx, Hc_ShopOrderDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlashActivitiesResponse)
	err := c.cc.Invoke(ctx, Hc_FlashActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hcClient) FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemResponse)
	err := c.cc.Invoke(ctx, Hc_FlashRedeem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HcServer is the server API for Hc service.
// All implementations must embed UnimplementedHcServer
// for forward compatibility.
//
// Hc 单一领域 rpc：合并 user / idle / task / shop 四个领域（2 进程架构：网关 + 本 rpc）。
// 方法名按领域加前缀（Idle*/Task*/Shop*），user 域方法名本身域特定故不加前缀。
// 域间协作（积分增减 / 任务进度）在进程内直接调用，不再走跨 rpc。
type HcServer interface {
	// ================= user 域：认证 + 用户 + 积分 =================
	// 邮箱注册，成功直接签发 token 对
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 邮箱密码登录
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Google OAuth 登录/注册
	GoogleOAuth(context.Context, *GoogleOAuthRequest) (*GoogleOAuthResponse, error)
	// 刷新 token
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	// 修改密码（校验旧密码，并使已签发 token 失效）
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	// 用户资料
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	// 积分余额
	GetPoints(context.Context, *GetPointsRequest) (*GetPointsResponse, error)
	// 加分（挂机/任务奖励入账）
	AddPoints(context.Context, *AddPointsRequest) (*AddPointsResponse, error)
	// 扣分（兑换扣款，余额不足报错）
	DeductPoints(context.Context, *DeductPointsRequest) (*DeductPointsResponse, error)
	// ================= idle 域：挂机 =================
	// 开始挂机（同设备幂等续期；设备数量超限报错）
	IdleStart(context.Context, *IdleStartRequest) (*IdleRecord, error)
	// 心跳上报（更新最后心跳时间）
	IdleHeartbeat(context.Context, *IdleHeartbeatRequest) (*Empty, error)
	// 停止全部设备挂机并结算
	IdleStop(context.Context, *IdleStopRequest) (*IdleRecord, error)
	// 停止指定设备挂机并结算
	IdleStopDevice(context.Context, *IdleStopDeviceRequest) (*IdleRecord, error)
	// 挂机状态（活跃会话 + 今日已赚积分）
	IdleStatus(context.Context, *IdleStatusRequest) (*IdleStatusResponse, error)
	// 历史记录（游标分页）
	IdleRecords(context.Context, *IdleRecordsRequest) (*IdleRecordsResponse, error)
	// ================= task 域：任务 =================
	// 任务列表（含当前用户进度）
	TaskList(context.Context, *TaskListRequest) (*TaskListResponse, error)
	// 进度总览
	TaskProgress(context.Context, *TaskProgressRequest) (*TaskProgressResponse, error)
	// 领取任务奖励（进程内调用 AddPoints 入账）
	TaskClaim(context.Context, *TaskClaimRequest) (*TaskClaimResponse, error)
	// 上报进度增量（登录/挂机结算/兑换完成事件驱动）
	ReportProgress(context.Context, *ReportProgressRequest) (*Empty, error)
	// ================= shop 域：商城 + 抢购 =================
	// 商品列表（游标分页 + 分类筛选）
	ShopItems(context.Context, *ShopItemsRequest) (*ShopItemsResponse, error)
	// 积分兑换（扣积分 + 扣库存 + 建单）
	ShopRedeem(context.Context, *ShopRedeemRequest) (*RedeemResponse, error)
	// 兑换订单列表
	ShopOrders(context.Context, *ShopOrdersRequest) (*ShopOrdersResponse, error)
	// 订单详情（校验归属）
	ShopOrderDetail(context.Context, *ShopOrderDetailRequest) (*OrderInfo, error)
	// 进行中的抢购活动列表
	FlashActivities(context.Context, *FlashActivitiesRequest) (*FlashActivitiesResponse, error)
	// 定时抢购（限量内入库，超出直接拒绝）
	FlashRedeem(context.Context, *FlashRedeemRequest) (*RedeemResponse, error)
	mustEmbedUnimplementedHcServer()
}

// UnimplementedHcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHcServer struct{}

func (UnimplementedHcServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHcServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedHcServer) GoogleOAuth(context.Context, *GoogleOAuthRequest) (*GoogleOAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoogleOAuth not implemented")
}
func (UnimplementedHcServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedHcServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedHcServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedHcServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedHcServer) GetPoints(context.Context, *GetPointsRequest) (*GetPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPoints not implemented")
}
func (UnimplementedHcServer) AddPoints(context.Context, *AddPointsRequest) (*AddPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPoints not implemented")
}
func (UnimplementedHcServer) DeductPoints(context.Context, *DeductPointsRequest) (*DeductPointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductPoints not implemented")
}
func (UnimplementedHcServer) IdleStart(context.Context, *IdleStartRequest) (*IdleRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleStart not implemented")
}
func (UnimplementedHcServer) IdleHeartbeat(context.Context, *IdleHeartbeatRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleHeartbeat not implemented")
}
func (UnimplementedHcServer) IdleStop(context.Context, *IdleStopRequest) (*IdleRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleStop not implemented")
}
func (UnimplementedHcServer) IdleStopDevice(context.Context, *IdleStopDeviceRequest) (*IdleRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleStopDevice not implemented")
}
func (UnimplementedHcServer) IdleStatus(context.Context, *IdleStatusRequest) (*IdleStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleStatus not implemented")
}
func (UnimplementedHcServer) IdleRecords(context.Context, *IdleRecordsRequest) (*IdleRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IdleRecords not implemented")
}
func (UnimplementedHcServer) TaskList(context.Context, *TaskListRequest) (*TaskListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskList not implemented")
}
func (UnimplementedHcServer) TaskProgress(context.Context, *TaskProgressRequest) (*TaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskProgress not implemented")
}
func (UnimplementedHcServer) TaskClaim(context.Context, *TaskClaimRequest) (*TaskClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaskClaim not implemented")
}
func (UnimplementedHcServer) ReportProgress(context.Context, *ReportProgressRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedHcServer) ShopItems(context.Context, *ShopItemsRequest) (*ShopItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShopItems not implemented")
}
func (UnimplementedHcServer) ShopRedeem(context.Context, *ShopRedeemRequest) (*RedeemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShopRedeem not implemented")
}
func (UnimplementedHcServer) ShopOrders(context.Context, *ShopOrdersRequest) (*ShopOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShopOrders not implemented")
}
func (UnimplementedHcServer) ShopOrderDetail(context.Context, *ShopOrderDetailRequest) (*OrderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method ShopOrderDetail not implemented")
}
func (UnimplementedHcServer) FlashActivities(context.Context, *FlashActivitiesRequest) (*FlashActivitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlashActivities not implemented")
}
func (UnimplementedHcServer) FlashRedeem(context.Context, *FlashRedeemRequest) (*RedeemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlashRedeem not implemented")
}
func (UnimplementedHcServer) mustEmbedUnimplementedHcServer() {}
func (UnimplementedHcServer) testEmbeddedByValue()            {}

// UnsafeHcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HcServer will
// result in compilation errors.
type UnsafeHcServer interface {
	mustEmbedUnimplementedHcServer()
}

func RegisterHcServer(s grpc.ServiceRegistrar, srv HcServer) {
	// If the following call panics, it indicates UnimplementedHcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hc_ServiceDesc, srv)
}

func _Hc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_GoogleOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleOAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).GoogleOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_GoogleOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).GoogleOAuth(ctx, req.(*GoogleOAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_GetPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).GetPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_GetPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).GetPoints(ctx, req.(*GetPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_AddPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).AddPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_AddPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).AddPoints(ctx, req.(*AddPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_DeductPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).DeductPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_DeductPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).DeductPoints(ctx, req.(*DeductPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleStart(ctx, req.(*IdleStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleHeartbeat(ctx, req.(*IdleHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleStop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleStop(ctx, req.(*IdleStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleStopDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleStopDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleStopDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleStopDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleStopDevice(ctx, req.(*IdleStopDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleStatus(ctx, req.(*IdleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_IdleRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdleRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).IdleRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_IdleRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).IdleRecords(ctx, req.(*IdleRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_TaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).TaskList(ctx, req.(*TaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_TaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).TaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_TaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).TaskProgress(ctx, req.(*TaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_TaskClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).TaskClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_TaskClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).TaskClaim(ctx, req.(*TaskClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ReportProgress(ctx, req.(*ReportProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ShopItems(ctx, req.(*ShopItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ShopRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ShopRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ShopRedeem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ShopRedeem(ctx, req.(*ShopRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ShopOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ShopOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ShopOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ShopOrders(ctx, req.(*ShopOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_ShopOrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShopOrderDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).ShopOrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_ShopOrderDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).ShopOrderDetail(ctx, req.(*ShopOrderDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_FlashActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).FlashActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_FlashActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).FlashActivities(ctx, req.(*FlashActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hc_FlashRedeem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashRedeemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HcServer).FlashRedeem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hc_FlashRedeem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HcServer).FlashRedeem(ctx, req.(*FlashRedeemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hc_ServiceDesc is the grpc.ServiceDesc for Hc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hc.Hc",
	HandlerType: (*HcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Hc_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Hc_Login_Handler,
		},
		{
			MethodName: "GoogleOAuth",
			Handler:    _Hc_GoogleOAuth_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Hc_RefreshToken_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Hc_ChangePassword_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Hc_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Hc_UpdateProfile_Handler,
		},
		{
			MethodName: "GetPoints",
			Handler:    _Hc_GetPoints_Handler,
		},
		{
			MethodName: "AddPoints",
			Handler:    _Hc_AddPoints_Handler,
		},
		{
			MethodName: "DeductPoints",
			Handler:    _Hc_DeductPoints_Handler,
		},
		{
			MethodName: "IdleStart",
			Handler:    _Hc_IdleStart_Handler,
		},
		{
			MethodName: "IdleHeartbeat",
			Handler:    _Hc_IdleHeartbeat_Handler,
		},
		{
			MethodName: "IdleStop",
			Handler:    _Hc_IdleStop_Handler,
		},
		{
			MethodName: "IdleStopDevice",
			Handler:    _Hc_IdleStopDevice_Handler,
		},
		{
			MethodName: "IdleStatus",
			Handler:    _Hc_IdleStatus_Handler,
		},
		{
			MethodName: "IdleRecords",
			Handler:    _Hc_IdleRecords_Handler,
		},
		{
			MethodName: "TaskList",
			Handler:    _Hc_TaskList_Handler,
		},
		{
			MethodName: "TaskProgress",
			Handler:    _Hc_TaskProgress_Handler,
		},
		{
			MethodName: "TaskClaim",
			Handler:    _Hc_TaskClaim_Handler,
		},
		{
			MethodName: "ReportProgress",
			Handler:    _Hc_ReportProgress_Handler,
		},
		{
			MethodName: "ShopItems",
			Handler:    _Hc_ShopItems_Handler,
		},
		{
			MethodName: "ShopRedeem",
			Handler:    _Hc_ShopRedeem_Handler,
		},
		{
			MethodName: "ShopOrders",
			Handler:    _Hc_ShopOrders_Handler,
		},
		{
			MethodName: "ShopOrderDetail",
			Handler:    _Hc_ShopOrderDetail_Handler,
		},
		{
			MethodName: "FlashActivities",
			Handler:    _Hc_FlashActivities_Handler,
		},
		{
			MethodName: "FlashRedeem",
			Handler:    _Hc_FlashRedeem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/rpc/hc.proto",
}
