// Code generated by goctl. DO NOT EDIT.
// Source: idle.proto（手写等价版，pb 生成后即可用）

package idle

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// Idle idle-rpc 客户端接口
	Idle interface {
		Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
		Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
		Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error)
	}

	defaultIdle struct {
		cli zrpc.Client
	}
)

// NewIdle 创建 idle-rpc 客户端
func NewIdle(cli zrpc.Client) Idle {
	return &defaultIdle{cli: cli}
}

func (m *defaultIdle) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.Start(ctx, in, opts...)
}

func (m *defaultIdle) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.Heartbeat(ctx, in, opts...)
}

func (m *defaultIdle) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.Stop(ctx, in, opts...)
}

func (m *defaultIdle) StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.StopDevice(ctx, in, opts...)
}

func (m *defaultIdle) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.Status(ctx, in, opts...)
}

func (m *defaultIdle) Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error) {
	client := NewIdleClient(m.cli.Conn())
	return client.Records(ctx, in, opts...)
}
