// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: app/idle/rpc/idle.proto

package idle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Idle_Start_FullMethodName      = "/idle.Idle/Start"
	Idle_Heartbeat_FullMethodName  = "/idle.Idle/Heartbeat"
	Idle_Stop_FullMethodName       = "/idle.Idle/Stop"
	Idle_StopDevice_FullMethodName = "/idle.Idle/StopDevice"
	Idle_Status_FullMethodName     = "/idle.Idle/Status"
	Idle_Records_FullMethodName    = "/idle.Idle/Records"
)

// Idle is the client API for Idle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 挂机服务
type Idle interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error)
}

type idleClient struct {
	cc grpc.ClientConnInterface
}

func NewIdle(cc grpc.ClientConnInterface) Idle {
	return &idleClient{cc}
}

func (c *idleClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Idle_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idleClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Idle_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idleClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Idle_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idleClient) StopDevice(ctx context.Context, in *StopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdleRecord)
	err := c.cc.Invoke(ctx, Idle_StopDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idleClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Idle_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idleClient) Records(ctx context.Context, in *RecordsRequest, opts ...grpc.CallOption) (*RecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordsResponse)
	err := c.cc.Invoke(ctx, Idle_Records_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdleServer is the server API for Idle service.
// All implementations must embed UnimplementedIdleServer
// for forward compatibility.
//
// 挂机服务
type IdleServer interface {
	Start(context.Context, *StartRequest) (*IdleRecord, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*Empty, error)
	Stop(context.Context, *StopRequest) (*IdleRecord, error)
	StopDevice(context.Context, *StopDeviceRequest) (*IdleRecord, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Records(context.Context, *RecordsRequest) (*RecordsResponse, error)
	mustEmbedUnimplementedIdleServer()
}

// UnimplementedIdleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdleServer struct{}

func (UnimplementedIdleServer) Start(context.Context, *StartRequest) (*IdleRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedIdleServer) Heartbeat(context.Context, *HeartbeatRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedIdleServer) Stop(context.Context, *StopRequest) (*IdleRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedIdleServer) StopDevice(context.Context, *StopDeviceRequest) (*IdleRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopDevice not implemented")
}
func (UnimplementedIdleServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedIdleServer) Records(context.Context, *RecordsRequest) (*RecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Records not implemented")
}
func (UnimplementedIdleServer) mustEmbedUnimplementedIdleServer() {}
func (UnimplementedIdleServer) testEmbeddedByValue()              {}

// UnsafeIdleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdleServer will
// result in compilation errors.
type UnsafeIdleServer interface {
	mustEmbedUnimplementedIdleServer()
}

func RegisterIdleServer(s grpc.ServiceRegistrar, srv IdleServer) {
	// If the following call pancis, it indicates UnimplementedIdleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Idle_ServiceDesc, srv)
}

func _Idle_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Idle_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Idle_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Idle_StopDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).StopDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_StopDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).StopDevice(ctx, req.(*StopDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Idle_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Idle_Records_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdleServer).Records(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Idle_Records_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdleServer).Records(ctx, req.(*RecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Idle_ServiceDesc is the grpc.ServiceDesc for Idle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Idle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idle.Idle",
	HandlerType: (*IdleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Idle_Start_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Idle_Heartbeat_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Idle_Stop_Handler,
		},
		{
			MethodName: "StopDevice",
			Handler:    _Idle_StopDevice_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Idle_Status_Handler,
		},
		{
			MethodName: "Records",
			Handler:    _Idle_Records_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/idle/rpc/idle.proto",
}
