// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: app/idle/rpc/idle.proto

package idle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{0}
}

type IdleRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StartTime       int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	PointsEarned    int64                  `protobuf:"varint,7,opt,name=points_earned,json=pointsEarned,proto3" json:"points_earned,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	LastHeartbeatAt int64                  `protobuf:"varint,9,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdleRecord) Reset() {
	*x = IdleRecord{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdleRecord) ProtoMessage() {}

func (x *IdleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdleRecord.ProtoReflect.Descriptor instead.
func (*IdleRecord) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{1}
}

func (x *IdleRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdleRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdleRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IdleRecord) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *IdleRecord) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *IdleRecord) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *IdleRecord) GetPointsEarned() int64 {
	if x != nil {
		return x.PointsEarned
	}
	return 0
}

func (x *IdleRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IdleRecord) GetLastHeartbeatAt() int64 {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return 0
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StopDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDeviceRequest) Reset() {
	*x = StopDeviceRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDeviceRequest) ProtoMessage() {}

func (x *StopDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDeviceRequest.ProtoReflect.Descriptor instead.
func (*StopDeviceRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{5}
}

func (x *StopDeviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StopDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*IdleRecord          `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	TodayPoints   int64                  `protobuf:"varint,2,opt,name=today_points,json=todayPoints,proto3" json:"today_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetRecords() []*IdleRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *StatusResponse) GetTodayPoints() int64 {
	if x != nil {
		return x.TodayPoints
	}
	return 0
}

type RecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cursor        int64                  `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsRequest) Reset() {
	*x = RecordsRequest{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsRequest) ProtoMessage() {}

func (x *RecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsRequest.ProtoReflect.Descriptor instead.
func (*RecordsRequest) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{8}
}

func (x *RecordsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordsRequest) GetCursor() int64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *RecordsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*IdleRecord          `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordsResponse) Reset() {
	*x = RecordsResponse{}
	mi := &file_app_idle_rpc_idle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordsResponse) ProtoMessage() {}

func (x *RecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_idle_rpc_idle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordsResponse.ProtoReflect.Descriptor instead.
func (*RecordsResponse) Descriptor() ([]byte, []int) {
	return file_app_idle_rpc_idle_proto_rawDescGZIP(), []int{9}
}

func (x *RecordsResponse) GetRecords() []*IdleRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecordsResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *RecordsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_app_idle_rpc_idle_proto protoreflect.FileDescriptor

const file_app_idle_rpc_idle_proto_rawDesc = "" +
	"\n" +
	"\x17app/idle/rpc/idle.proto\x12\x04idle\"\a\n" +
	"\x05Empty\"\xa0\x02\n" +
	"\n" +
	"IdleRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x05R\x0fdurationSeconds\x12#\n" +
	"\rpoints_earned\x18\a \x01(\x03R\fpointsEarned\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12*\n" +
	"\x11last_heartbeat_at\x18\t \x01(\x03R\x0flastHeartbeatAt\"D\n" +
	"\fStartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"H\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"&\n" +
	"\vStopRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x11StopDeviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"_\n" +
	"\x0eStatusResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.idle.IdleRecordR\arecords\x12!\n" +
	"\ftoday_points\x18\x02 \x01(\x03R\vtodayPoints\"W\n" +
	"\x0eRecordsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x03R\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"y\n" +
	"\x0fRecordsResponse\x12*\n" +
	"\arecords\x18\x01 \x03(\v2\x10.idle.IdleRecordR\arecords\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xba\x02\n" +
	"\x04Idle\x12-\n" +
	"\x05Start\x12\x12.idle.StartRequest\x1a\x10.idle.IdleRecord\x120\n" +
	"\tHeartbeat\x12\x16.idle.HeartbeatRequest\x1a\v.idle.Empty\x12+\n" +
	"\x04Stop\x12\x11.idle.StopRequest\x1a\x10.idle.IdleRecord\x127\n" +
	"\n" +
	"StopDevice\x12\x17.idle.StopDeviceRequest\x1a\x10.idle.IdleRecord\x123\n" +
	"\x06Status\x12\x13.idle.StatusRequest\x1a\x14.idle.StatusResponse\x126\n" +
	"\aRecords\x12\x14.idle.RecordsRequest\x1a\x15.idle.RecordsResponseB4Z2github.com/cdcdx/hc-framework-go/app/idle/rpc/idleb\x06proto3"

var (
	file_app_idle_rpc_idle_proto_rawDescOnce sync.Once
	file_app_idle_rpc_idle_proto_rawDescData []byte
)

func file_app_idle_rpc_idle_proto_rawDescGZIP() []byte {
	file_app_idle_rpc_idle_proto_rawDescOnce.Do(func() {
		file_app_idle_rpc_idle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_idle_rpc_idle_proto_rawDesc), len(file_app_idle_rpc_idle_proto_rawDesc)))
	})
	return file_app_idle_rpc_idle_proto_rawDescData
}

var file_app_idle_rpc_idle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_idle_rpc_idle_proto_goTypes = []any{
	(*Empty)(nil),             // 0: idle.Empty
	(*IdleRecord)(nil),        // 1: idle.IdleRecord
	(*StartRequest)(nil),      // 2: idle.StartRequest
	(*HeartbeatRequest)(nil),  // 3: idle.HeartbeatRequest
	(*StopRequest)(nil),       // 4: idle.StopRequest
	(*StopDeviceRequest)(nil), // 5: idle.StopDeviceRequest
	(*StatusRequest)(nil),     // 6: idle.StatusRequest
	(*StatusResponse)(nil),    // 7: idle.StatusResponse
	(*RecordsRequest)(nil),    // 8: idle.RecordsRequest
	(*RecordsResponse)(nil),   // 9: idle.RecordsResponse
}
var file_app_idle_rpc_idle_proto_depIdxs = []int32{
	1, // 0: idle.StatusResponse.records:type_name -> idle.IdleRecord
	1, // 1: idle.RecordsResponse.records:type_name -> idle.IdleRecord
	2, // 2: idle.Idle.Start:input_type -> idle.StartRequest
	3, // 3: idle.Idle.Heartbeat:input_type -> idle.HeartbeatRequest
	4, // 4: idle.Idle.Stop:input_type -> idle.StopRequest
	5, // 5: idle.Idle.StopDevice:input_type -> idle.StopDeviceRequest
	6, // 6: idle.Idle.Status:input_type -> idle.StatusRequest
	8, // 7: idle.Idle.Records:input_type -> idle.RecordsRequest
	1, // 8: idle.Idle.Start:output_type -> idle.IdleRecord
	0, // 9: idle.Idle.Heartbeat:output_type -> idle.Empty
	1, // 10: idle.Idle.Stop:output_type -> idle.IdleRecord
	1, // 11: idle.Idle.StopDevice:output_type -> idle.IdleRecord
	7, // 12: idle.Idle.Status:output_type -> idle.StatusResponse
	9, // 13: idle.Idle.Records:output_type -> idle.RecordsResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_idle_rpc_idle_proto_init() }
func file_app_idle_rpc_idle_proto_init() {
	if File_app_idle_rpc_idle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_idle_rpc_idle_proto_rawDesc), len(file_app_idle_rpc_idle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_idle_rpc_idle_proto_goTypes,
		DependencyIndexes: file_app_idle_rpc_idle_proto_depIdxs,
		MessageInfos:      file_app_idle_rpc_idle_proto_msgTypes,
	}.Build()
	File_app_idle_rpc_idle_proto = out.File
	file_app_idle_rpc_idle_proto_goTypes = nil
	file_app_idle_rpc_idle_proto_depIdxs = nil
}
