// Code generated by goctl. DO NOT EDIT.
// Source: hc.proto（手写等价版，pb 生成后即可用）

package hc

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// Hc 单一领域 rpc 客户端接口
	Hc interface {
		// user 域
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GoogleOAuth(ctx context.Context, in *GoogleOAuthRequest, opts ...grpc.CallOption) (*GoogleOAuthResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
		GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
		GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error)
		AddPoints(ctx context.Context, in *AddPointsRequest, opts ...grpc.CallOption) (*AddPointsResponse, error)
		DeductPoints(ctx context.Context, in *DeductPointsRequest, opts ...grpc.CallOption) (*DeductPointsResponse, error)
		// idle 域
		IdleStart(ctx context.Context, in *IdleStartRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		IdleHeartbeat(ctx context.Context, in *IdleHeartbeatRequest, opts ...grpc.CallOption) (*Empty, error)
		IdleStop(ctx context.Context, in *IdleStopRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		IdleStopDevice(ctx context.Context, in *IdleStopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error)
		IdleStatus(ctx context.Context, in *IdleStatusRequest, opts ...grpc.CallOption) (*IdleStatusResponse, error)
		IdleRecords(ctx context.Context, in *IdleRecordsRequest, opts ...grpc.CallOption) (*IdleRecordsResponse, error)
		// task 域
		TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error)
		TaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (*TaskProgressResponse, error)
		TaskClaim(ctx context.Context, in *TaskClaimRequest, opts ...grpc.CallOption) (*TaskClaimResponse, error)
		ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error)
		// shop 域
		ShopItems(ctx context.Context, in *ShopItemsRequest, opts ...grpc.CallOption) (*ShopItemsResponse, error)
		ShopRedeem(ctx context.Context, in *ShopRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
		ShopOrders(ctx context.Context, in *ShopOrdersRequest, opts ...grpc.CallOption) (*ShopOrdersResponse, error)
		ShopOrderDetail(ctx context.Context, in *ShopOrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error)
		FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error)
		FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error)
	}

	defaultHc struct {
		cli zrpc.Client
	}
)

// NewHc 创建 hc-rpc 客户端
func NewHc(cli zrpc.Client) Hc {
	return &defaultHc{cli: cli}
}

func (m *defaultHc) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultHc) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultHc) GoogleOAuth(ctx context.Context, in *GoogleOAuthRequest, opts ...grpc.CallOption) (*GoogleOAuthResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.GoogleOAuth(ctx, in, opts...)
}

func (m *defaultHc) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultHc) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

func (m *defaultHc) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.GetProfile(ctx, in, opts...)
}

func (m *defaultHc) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

func (m *defaultHc) GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.GetPoints(ctx, in, opts...)
}

func (m *defaultHc) AddPoints(ctx context.Context, in *AddPointsRequest, opts ...grpc.CallOption) (*AddPointsResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.AddPoints(ctx, in, opts...)
}

func (m *defaultHc) DeductPoints(ctx context.Context, in *DeductPointsRequest, opts ...grpc.CallOption) (*DeductPointsResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.DeductPoints(ctx, in, opts...)
}

func (m *defaultHc) IdleStart(ctx context.Context, in *IdleStartRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleStart(ctx, in, opts...)
}

func (m *defaultHc) IdleHeartbeat(ctx context.Context, in *IdleHeartbeatRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleHeartbeat(ctx, in, opts...)
}

func (m *defaultHc) IdleStop(ctx context.Context, in *IdleStopRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleStop(ctx, in, opts...)
}

func (m *defaultHc) IdleStopDevice(ctx context.Context, in *IdleStopDeviceRequest, opts ...grpc.CallOption) (*IdleRecord, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleStopDevice(ctx, in, opts...)
}

func (m *defaultHc) IdleStatus(ctx context.Context, in *IdleStatusRequest, opts ...grpc.CallOption) (*IdleStatusResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleStatus(ctx, in, opts...)
}

func (m *defaultHc) IdleRecords(ctx context.Context, in *IdleRecordsRequest, opts ...grpc.CallOption) (*IdleRecordsResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.IdleRecords(ctx, in, opts...)
}

func (m *defaultHc) TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.TaskList(ctx, in, opts...)
}

func (m *defaultHc) TaskProgress(ctx context.Context, in *TaskProgressRequest, opts ...grpc.CallOption) (*TaskProgressResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.TaskProgress(ctx, in, opts...)
}

func (m *defaultHc) TaskClaim(ctx context.Context, in *TaskClaimRequest, opts ...grpc.CallOption) (*TaskClaimResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.TaskClaim(ctx, in, opts...)
}

func (m *defaultHc) ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ReportProgress(ctx, in, opts...)
}

func (m *defaultHc) ShopItems(ctx context.Context, in *ShopItemsRequest, opts ...grpc.CallOption) (*ShopItemsResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ShopItems(ctx, in, opts...)
}

func (m *defaultHc) ShopRedeem(ctx context.Context, in *ShopRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ShopRedeem(ctx, in, opts...)
}

func (m *defaultHc) ShopOrders(ctx context.Context, in *ShopOrdersRequest, opts ...grpc.CallOption) (*ShopOrdersResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ShopOrders(ctx, in, opts...)
}

func (m *defaultHc) ShopOrderDetail(ctx context.Context, in *ShopOrderDetailRequest, opts ...grpc.CallOption) (*OrderInfo, error) {
	client := NewHcClient(m.cli.Conn())
	return client.ShopOrderDetail(ctx, in, opts...)
}

func (m *defaultHc) FlashActivities(ctx context.Context, in *FlashActivitiesRequest, opts ...grpc.CallOption) (*FlashActivitiesResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.FlashActivities(ctx, in, opts...)
}

func (m *defaultHc) FlashRedeem(ctx context.Context, in *FlashRedeemRequest, opts ...grpc.CallOption) (*RedeemResponse, error) {
	client := NewHcClient(m.cli.Conn())
	return client.FlashRedeem(ctx, in, opts...)
}
