// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: app/user/rpc/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	PointsBalance int64                  `protobuf:"varint,5,opt,name=points_balance,json=pointsBalance,proto3" json:"points_balance,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetPointsBalance() int64 {
	if x != nil {
		return x.PointsBalance
	}
	return 0
}

func (x *UserInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GoogleOAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleOAuthRequest) Reset() {
	*x = GoogleOAuthRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleOAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleOAuthRequest) ProtoMessage() {}

func (x *GoogleOAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleOAuthRequest.ProtoReflect.Descriptor instead.
func (*GoogleOAuthRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleOAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GoogleOAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleOAuthResponse) Reset() {
	*x = GoogleOAuthResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleOAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleOAuthResponse) ProtoMessage() {}

func (x *GoogleOAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleOAuthResponse.ProtoReflect.Descriptor instead.
func (*GoogleOAuthResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *GoogleOAuthResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GoogleOAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GoogleOAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type GetPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsRequest) Reset() {
	*x = GetPointsRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsRequest) ProtoMessage() {}

func (x *GetPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsRequest.ProtoReflect.Descriptor instead.
func (*GetPointsRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PointsBalance int64                  `protobuf:"varint,2,opt,name=points_balance,json=pointsBalance,proto3" json:"points_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPointsResponse) Reset() {
	*x = GetPointsResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPointsResponse) ProtoMessage() {}

func (x *GetPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPointsResponse.ProtoReflect.Descriptor instead.
func (*GetPointsResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetPointsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPointsResponse) GetPointsBalance() int64 {
	if x != nil {
		return x.PointsBalance
	}
	return 0
}

type AddPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Points        int64                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsRequest) Reset() {
	*x = AddPointsRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsRequest) ProtoMessage() {}

func (x *AddPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsRequest.ProtoReflect.Descriptor instead.
func (*AddPointsRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *AddPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPointsRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *AddPointsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PointsBalance int64                  `protobuf:"varint,2,opt,name=points_balance,json=pointsBalance,proto3" json:"points_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPointsResponse) Reset() {
	*x = AddPointsResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPointsResponse) ProtoMessage() {}

func (x *AddPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPointsResponse.ProtoReflect.Descriptor instead.
func (*AddPointsResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *AddPointsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPointsResponse) GetPointsBalance() int64 {
	if x != nil {
		return x.PointsBalance
	}
	return 0
}

type DeductPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Points        int64                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductPointsRequest) Reset() {
	*x = DeductPointsRequest{}
	mi := &file_app_user_rpc_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductPointsRequest) ProtoMessage() {}

func (x *DeductPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductPointsRequest.ProtoReflect.Descriptor instead.
func (*DeductPointsRequest) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{19}
}

func (x *DeductPointsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductPointsRequest) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *DeductPointsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeductPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PointsBalance int64                  `protobuf:"varint,2,opt,name=points_balance,json=pointsBalance,proto3" json:"points_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductPointsResponse) Reset() {
	*x = DeductPointsResponse{}
	mi := &file_app_user_rpc_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductPointsResponse) ProtoMessage() {}

func (x *DeductPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_rpc_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductPointsResponse.ProtoReflect.Descriptor instead.
func (*DeductPointsResponse) Descriptor() ([]byte, []int) {
	return file_app_user_rpc_user_proto_rawDescGZIP(), []int{20}
}

func (x *DeductPointsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductPointsResponse) GetPointsBalance() int64 {
	if x != nil {
		return x.PointsBalance
	}
	return 0
}

var File_app_user_rpc_user_proto protoreflect.FileDescriptor

const file_app_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x17app/user/rpc/user.proto\x12\x04user\"\xd2\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12%\n" +
	"\x0epoints_balance\x18\x05 \x01(\x03R\rpointsBalance\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"~\n" +
	"\x10RegisterResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"{\n" +
	"\rLoginResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\"(\n" +
	"\x12GoogleOAuthRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x81\x01\n" +
	"\x13GoogleOAuthResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"v\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x12GetProfileResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"j\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\";\n" +
	"\x15UpdateProfileResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"+\n" +
	"\x10GetPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x11GetPointsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0epoints_balance\x18\x02 \x01(\x03R\rpointsBalance\"[\n" +
	"\x10AddPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x03R\x06points\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"S\n" +
	"\x11AddPointsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0epoints_balance\x18\x02 \x01(\x03R\rpointsBalance\"^\n" +
	"\x13DeductPointsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x03R\x06points\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"V\n" +
	"\x14DeductPointsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0epoints_balance\x18\x02 \x01(\x03R\rpointsBalance2\x99\x05\n" +
	"\x04User\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12B\n" +
	"\vGoogleOAuth\x12\x18.user.GoogleOAuthRequest\x1a\x19.user.GoogleOAuthResponse\x12E\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponse\x12K\n" +
	"\x0eChangePassword\x12\x1b.user.ChangePasswordRequest\x1a\x1c.user.ChangePasswordResponse\x12?\n" +
	"\n" +
	"GetProfile\x12\x17.user.GetProfileRequest\x1a\x18.user.GetProfileResponse\x12H\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x1b.user.UpdateProfileResponse\x12<\n" +
	"\tGetPoints\x12\x16.user.GetPointsRequest\x1a\x17.user.GetPointsResponse\x12<\n" +
	"\tAddPoints\x12\x16.user.AddPointsRequest\x1a\x17.user.AddPointsResponse\x12E\n" +
	"\fDeductPoints\x12\x19.user.DeductPointsRequest\x1a\x1a.user.DeductPointsResponseB4Z2github.com/cdcdx/hc-framework-go/app/user/rpc/userb\x06proto3"

var (
	file_app_user_rpc_user_proto_rawDescOnce sync.Once
	file_app_user_rpc_user_proto_rawDescData []byte
)

func file_app_user_rpc_user_proto_rawDescGZIP() []byte {
	file_app_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_app_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)))
	})
	return file_app_user_rpc_user_proto_rawDescData
}

var file_app_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_app_user_rpc_user_proto_goTypes = []any{
	(*UserInfo)(nil),               // 0: user.UserInfo
	(*RegisterRequest)(nil),        // 1: user.RegisterRequest
	(*RegisterResponse)(nil),       // 2: user.RegisterResponse
	(*LoginRequest)(nil),           // 3: user.LoginRequest
	(*LoginResponse)(nil),          // 4: user.LoginResponse
	(*GoogleOAuthRequest)(nil),     // 5: user.GoogleOAuthRequest
	(*GoogleOAuthResponse)(nil),    // 6: user.GoogleOAuthResponse
	(*RefreshTokenRequest)(nil),    // 7: user.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 8: user.RefreshTokenResponse
	(*ChangePasswordRequest)(nil),  // 9: user.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 10: user.ChangePasswordResponse
	(*GetProfileRequest)(nil),      // 11: user.GetProfileRequest
	(*GetProfileResponse)(nil),     // 12: user.GetProfileResponse
	(*UpdateProfileRequest)(nil),   // 13: user.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 14: user.UpdateProfileResponse
	(*GetPointsRequest)(nil),       // 15: user.GetPointsRequest
	(*GetPointsResponse)(nil),      // 16: user.GetPointsResponse
	(*AddPointsRequest)(nil),       // 17: user.AddPointsRequest
	(*AddPointsResponse)(nil),      // 18: user.AddPointsResponse
	(*DeductPointsRequest)(nil),    // 19: user.DeductPointsRequest
	(*DeductPointsResponse)(nil),   // 20: user.DeductPointsResponse
}
var file_app_user_rpc_user_proto_depIdxs = []int32{
	0,  // 0: user.RegisterResponse.user:type_name -> user.UserInfo
	0,  // 1: user.LoginResponse.user:type_name -> user.UserInfo
	0,  // 2: user.GoogleOAuthResponse.user:type_name -> user.UserInfo
	0,  // 3: user.GetProfileResponse.user:type_name -> user.UserInfo
	0,  // 4: user.UpdateProfileResponse.user:type_name -> user.UserInfo
	1,  // 5: user.User.Register:input_type -> user.RegisterRequest
	3,  // 6: user.User.Login:input_type -> user.LoginRequest
	5,  // 7: user.User.GoogleOAuth:input_type -> user.GoogleOAuthRequest
	7,  // 8: user.User.RefreshToken:input_type -> user.RefreshTokenRequest
	9,  // 9: user.User.ChangePassword:input_type -> user.ChangePasswordRequest
	11, // 10: user.User.GetProfile:input_type -> user.GetProfileRequest
	13, // 11: user.User.UpdateProfile:input_type -> user.UpdateProfileRequest
	15, // 12: user.User.GetPoints:input_type -> user.GetPointsRequest
	17, // 13: user.User.AddPoints:input_type -> user.AddPointsRequest
	19, // 14: user.User.DeductPoints:input_type -> user.DeductPointsRequest
	2,  // 15: user.User.Register:output_type -> user.RegisterResponse
	4,  // 16: user.User.Login:output_type -> user.LoginResponse
	6,  // 17: user.User.GoogleOAuth:output_type -> user.GoogleOAuthResponse
	8,  // 18: user.User.RefreshToken:output_type -> user.RefreshTokenResponse
	10, // 19: user.User.ChangePassword:output_type -> user.ChangePasswordResponse
	12, // 20: user.User.GetProfile:output_type -> user.GetProfileResponse
	14, // 21: user.User.UpdateProfile:output_type -> user.UpdateProfileResponse
	16, // 22: user.User.GetPoints:output_type -> user.GetPointsResponse
	18, // 23: user.User.AddPoints:output_type -> user.AddPointsResponse
	20, // 24: user.User.DeductPoints:output_type -> user.DeductPointsResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_app_user_rpc_user_proto_init() }
func file_app_user_rpc_user_proto_init() {
	if File_app_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_rpc_user_proto_rawDesc), len(file_app_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_app_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_app_user_rpc_user_proto_msgTypes,
	}.Build()
	File_app_user_rpc_user_proto = out.File
	file_app_user_rpc_user_proto_goTypes = nil
	file_app_user_rpc_user_proto_depIdxs = nil
}
