// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: app/task/rpc/task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskType        string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TaskKey         string                 `protobuf:"bytes,3,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	TaskName        string                 `protobuf:"bytes,4,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	TargetValue     int32                  `protobuf:"varint,5,opt,name=target_value,json=targetValue,proto3" json:"target_value,omitempty"`
	RewardPoints    int64                  `protobuf:"varint,6,opt,name=reward_points,json=rewardPoints,proto3" json:"reward_points,omitempty"`
	IsActive        bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Period          string                 `protobuf:"bytes,8,opt,name=period,proto3" json:"period,omitempty"`
	CurrentProgress int32                  `protobuf:"varint,9,opt,name=current_progress,json=currentProgress,proto3" json:"current_progress,omitempty"`
	IsCompleted     bool                   `protobuf:"varint,10,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsClaimed       bool                   `protobuf:"varint,11,opt,name=is_claimed,json=isClaimed,proto3" json:"is_claimed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_app_task_rpc_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskInfo) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskInfo) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *TaskInfo) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskInfo) GetTargetValue() int32 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

func (x *TaskInfo) GetRewardPoints() int64 {
	if x != nil {
		return x.RewardPoints
	}
	return 0
}

func (x *TaskInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *TaskInfo) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TaskInfo) GetCurrentProgress() int32 {
	if x != nil {
		return x.CurrentProgress
	}
	return 0
}

func (x *TaskInfo) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *TaskInfo) GetIsClaimed() bool {
	if x != nil {
		return x.IsClaimed
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_app_task_rpc_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_app_task_rpc_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_app_task_rpc_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{3}
}

func (x *ProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_app_task_rpc_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_app_task_rpc_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClaimRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskInfo              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	RewardPoints  int64                  `protobuf:"varint,2,opt,name=reward_points,json=rewardPoints,proto3" json:"reward_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_app_task_rpc_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimResponse) GetTask() *TaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ClaimResponse) GetRewardPoints() int64 {
	if x != nil {
		return x.RewardPoints
	}
	return 0
}

type ReportProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskKey       string                 `protobuf:"bytes,2,opt,name=task_key,json=taskKey,proto3" json:"task_key,omitempty"`
	Delta         int32                  `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProgressRequest) Reset() {
	*x = ReportProgressRequest{}
	mi := &file_app_task_rpc_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressRequest) ProtoMessage() {}

func (x *ReportProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressRequest.ProtoReflect.Descriptor instead.
func (*ReportProgressRequest) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{7}
}

func (x *ReportProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReportProgressRequest) GetTaskKey() string {
	if x != nil {
		return x.TaskKey
	}
	return ""
}

func (x *ReportProgressRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ReportProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskInfo              `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportProgressResponse) Reset() {
	*x = ReportProgressResponse{}
	mi := &file_app_task_rpc_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportProgressResponse) ProtoMessage() {}

func (x *ReportProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_task_rpc_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportProgressResponse.ProtoReflect.Descriptor instead.
func (*ReportProgressResponse) Descriptor() ([]byte, []int) {
	return file_app_task_rpc_task_proto_rawDescGZIP(), []int{8}
}

func (x *ReportProgressResponse) GetTask() *TaskInfo {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ReportProgressResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_app_task_rpc_task_proto protoreflect.FileDescriptor

const file_app_task_rpc_task_proto_rawDesc = "" +
	"\n" +
	"\x17app/task/rpc/task.proto\x12\x04task\"\xd9\x02\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x19\n" +
	"\btask_key\x18\x03 \x01(\tR\ataskKey\x12\x1b\n" +
	"\ttask_name\x18\x04 \x01(\tR\btaskName\x12!\n" +
	"\ftarget_value\x18\x05 \x01(\x05R\vtargetValue\x12#\n" +
	"\rreward_points\x18\x06 \x01(\x03R\frewardPoints\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x16\n" +
	"\x06period\x18\b \x01(\tR\x06period\x12)\n" +
	"\x10current_progress\x18\t \x01(\x05R\x0fcurrentProgress\x12!\n" +
	"\fis_completed\x18\n" +
	" \x01(\bR\visCompleted\x12\x1d\n" +
	"\n" +
	"is_claimed\x18\v \x01(\bR\tisClaimed\"&\n" +
	"\vListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\fListResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.task.TaskInfoR\x05tasks\"*\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x10ProgressResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.task.TaskInfoR\x05tasks\"@\n" +
	"\fClaimRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\"X\n" +
	"\rClaimResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.task.TaskInfoR\x04task\x12#\n" +
	"\rreward_points\x18\x02 \x01(\x03R\frewardPoints\"a\n" +
	"\x15ReportProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\btask_key\x18\x02 \x01(\tR\ataskKey\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x05R\x05delta\"Z\n" +
	"\x16ReportProgressResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.task.TaskInfoR\x04task\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\bR\tcompleted2\xef\x01\n" +
	"\x04Task\x12-\n" +
	"\x04List\x12\x11.task.ListRequest\x1a\x12.task.ListResponse\x129\n" +
	"\bProgress\x12\x15.task.ProgressRequest\x1a\x16.task.ProgressResponse\x120\n" +
	"\x05Claim\x12\x12.task.ClaimRequest\x1a\x13.task.ClaimResponse\x12K\n" +
	"\x0eReportProgress\x12\x1b.task.ReportProgressRequest\x1a\x1c.task.ReportProgressResponseB4Z2github.com/cdcdx/hc-framework-go/app/task/rpc/taskb\x06proto3"

var (
	file_app_task_rpc_task_proto_rawDescOnce sync.Once
	file_app_task_rpc_task_proto_rawDescData []byte
)

func file_app_task_rpc_task_proto_rawDescGZIP() []byte {
	file_app_task_rpc_task_proto_rawDescOnce.Do(func() {
		file_app_task_rpc_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_task_rpc_task_proto_rawDesc), len(file_app_task_rpc_task_proto_rawDesc)))
	})
	return file_app_task_rpc_task_proto_rawDescData
}

var file_app_task_rpc_task_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_task_rpc_task_proto_goTypes = []any{
	(*TaskInfo)(nil),               // 0: task.TaskInfo
	(*ListRequest)(nil),            // 1: task.ListRequest
	(*ListResponse)(nil),           // 2: task.ListResponse
	(*ProgressRequest)(nil),        // 3: task.ProgressRequest
	(*ProgressResponse)(nil),       // 4: task.ProgressResponse
	(*ClaimRequest)(nil),           // 5: task.ClaimRequest
	(*ClaimResponse)(nil),          // 6: task.ClaimResponse
	(*ReportProgressRequest)(nil),  // 7: task.ReportProgressRequest
	(*ReportProgressResponse)(nil), // 8: task.ReportProgressResponse
}
var file_app_task_rpc_task_proto_depIdxs = []int32{
	0, // 0: task.ListResponse.tasks:type_name -> task.TaskInfo
	0, // 1: task.ProgressResponse.tasks:type_name -> task.TaskInfo
	0, // 2: task.ClaimResponse.task:type_name -> task.TaskInfo
	0, // 3: task.ReportProgressResponse.task:type_name -> task.TaskInfo
	1, // 4: task.Task.List:input_type -> task.ListRequest
	3, // 5: task.Task.Progress:input_type -> task.ProgressRequest
	5, // 6: task.Task.Claim:input_type -> task.ClaimRequest
	7, // 7: task.Task.ReportProgress:input_type -> task.ReportProgressRequest
	2, // 8: task.Task.List:output_type -> task.ListResponse
	4, // 9: task.Task.Progress:output_type -> task.ProgressResponse
	6, // 10: task.Task.Claim:output_type -> task.ClaimResponse
	8, // 11: task.Task.ReportProgress:output_type -> task.ReportProgressResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_task_rpc_task_proto_init() }
func file_app_task_rpc_task_proto_init() {
	if File_app_task_rpc_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_task_rpc_task_proto_rawDesc), len(file_app_task_rpc_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_task_rpc_task_proto_goTypes,
		DependencyIndexes: file_app_task_rpc_task_proto_depIdxs,
		MessageInfos:      file_app_task_rpc_task_proto_msgTypes,
	}.Build()
	File_app_task_rpc_task_proto = out.File
	file_app_task_rpc_task_proto_goTypes = nil
	file_app_task_rpc_task_proto_depIdxs = nil
}
