// Code generated by goctl. DO NOT EDIT.
// Source: task.proto（手写等价版，pb 生成后即可用）

package task

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	// Task task-rpc 客户端接口
	Task interface {
		List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
		Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
		Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
		ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultTask struct {
		cli zrpc.Client
	}
)

// NewTask 创建 task-rpc 客户端
func NewTask(cli zrpc.Client) Task {
	return &defaultTask{cli: cli}
}

func (m *defaultTask) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	client := NewTaskClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultTask) Progress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	client := NewTaskClient(m.cli.Conn())
	return client.Progress(ctx, in, opts...)
}

func (m *defaultTask) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	client := NewTaskClient(m.cli.Conn())
	return client.Claim(ctx, in, opts...)
}

func (m *defaultTask) ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := NewTaskClient(m.cli.Conn())
	return client.ReportProgress(ctx, in, opts...)
}
